### ISSUE TITLE
Data preparation scripts

### ISSUE THREAD

**Issue by erees1** [30stomercury/autoregressive-co-training#1]
Hi, thanks for the repostiory and the paper! I am trying to reproduce the results from your paper and am finding it unclear exactly what data prep you have done. Are you able to share the scripts you used to prepare the Kaldi scp files and ark files? Thanks!

**Comment by 30stomercury** [comment]
Hi, sorry for the late reply.
It's just standard kaldi script. Which part of data prep in the paper you found it unclear?

Thanks.

**Comment by erees1** [comment]
Thanks for the reply are you able to point me to the one you used? The main thing I'm looking for is the parameters for creating the features that you have used.

**Comment by 30stomercury** [comment]
Hi, the `config/fbank.conf` is:

```
--window-type=hamming # disable Dans window, use the standard
--use-energy=false    # only fbank outputs
--num-mel-bins=40
```

Hope this is helpful.

**Comment by 30stomercury** [comment]
Hi, have you been able to reproduce it?

If no further questions I'll close the issue. Thanks!

**Comment by erees1** [comment]
Thanks @30stomercury I hadn't had a chance to action this yet but will reopen if I have further issues!
